version: "3.7"

services:
    spring-backend:
        image: shawnroshan/apricot.and.nut:spring-backend
        container_name: spring-backend
        # build:
        #   context: backend
        #   dockerfile: Dockerfile
        ports:
            - "80:8080"
            - "8080:8080"
        restart: always
        depends_on:
            - db
            - node-backend
        # networks:
        #     - backend
        #     - frontend

    node-backend:
        image: shawnroshan/apricot.and.nut:node-backend
        container_name: node-backend
        #build:
        #   context: node-backend
        #   dockerfile: Dockerfile
        environment:
            - SPRING_API_URL=http://spring-backend:8080/api
        ports:
            - "5000:5000"
        restart: always
        # networks:
        #     - backend

    db:
        image: mysql:8.0
        volumes:
            - db_data:/var/lib/mysql
        container_name: db
        ports:
            - "3308:3306"
        expose:
            - "3306"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: retaildb
        # networks:
        #     - backend

volumes:
    db_data:
    #customer-web:
    #container_name: customer-web
    #build:
    #    context: frontend/customer-web-app
    #   dockerfile: Dockerfile
    #ports:
    #    - "3000:3000"
    #restart: always
